Algoritmo "Exercício 02"
//Faça um algoritmo para calcular o consumo de combustível. O algoritmo deverá
//ler a quantidade de litros e a quantidade de quilômetros percorridos e o
//algoritmo deverá escrever na tela quantos Km o veículo está fazendo com um
//litro de combustível.
Var
L, Q, D : real
Inicio
escreva(" Km rodados:")
leia (Q)
escreva("Consumo de combustível:")
leia (L)
D <- Q/L
escreva("Seu veículo esta fazendo",D,"Km por litro")

Fimalgoritmo