Algoritmo "Exercício 03 (Semana 02)
//Faça um algoritmo que leia um nº inteiro e mostre uma mensagem indicando se
//este número é par ou ímpar, se é positivo ou negativo.
var N : inteiro
inicio
escreva("Digite um número inteiro: ")
leia(N)
se(N%2=0)entao
 escreva("O número é par")
senao
 escreva("O número é ímpar")
fimse
   se(N>=0)entao
    escreva(", e é positivo.")
   senao
    escreva(", e é negativo.")
Fimse
fimalgoritmo